import type { BankRule } from '@/lib/types'

export const initialRules: BankRule[] = [
  // Amount Rules
  {
    id: 'rule-001',
    name: 'High Value Transaction Alert',
    description: 'Flag transactions exceeding ₹1,00,000 for manual review',
    category: 'amount',
    severity: 'medium',
    isActive: true,
    threshold: 100000,
    action: 'review',
  },
  {
    id: 'rule-002',
    name: 'Very High Value Block',
    description: 'Block and hold transactions exceeding ₹5,00,000 until verified',
    category: 'amount',
    severity: 'critical',
    isActive: true,
    threshold: 500000,
    action: 'block',
  },
  {
    id: 'rule-003',
    name: 'Micro Transaction Pattern',
    description: 'Detect multiple small transactions under ₹500 in quick succession (possible card testing)',
    category: 'amount',
    severity: 'high',
    isActive: true,
    threshold: 500,
    action: 'flag',
  },

  // Location Rules
  {
    id: 'rule-004',
    name: 'Cross-State Rapid Transaction',
    description: 'Flag if transactions occur in different states within 30 minutes',
    category: 'location',
    severity: 'high',
    isActive: true,
    action: 'flag',
  },
  {
    id: 'rule-005',
    name: 'VPN/Proxy Detection',
    description: 'Block transactions originating from known VPN or proxy servers',
    category: 'location',
    severity: 'critical',
    isActive: true,
    action: 'block',
  },
  {
    id: 'rule-006',
    name: 'International Location Alert',
    description: 'Notify customer service when transaction location differs from registered address country',
    category: 'location',
    severity: 'medium',
    isActive: true,
    action: 'notify',
  },

  // Time-Based Rules
  {
    id: 'rule-007',
    name: 'Late Night Transaction Review',
    description: 'Flag transactions between 12 AM - 5 AM for additional verification',
    category: 'time',
    severity: 'medium',
    isActive: true,
    action: 'review',
  },
  {
    id: 'rule-008',
    name: 'Holiday Fraud Protection',
    description: 'Enhanced monitoring during bank holidays and weekends',
    category: 'time',
    severity: 'low',
    isActive: true,
    action: 'flag',
  },
  {
    id: 'rule-009',
    name: 'First Transaction After Dormancy',
    description: 'Flag large transactions from accounts inactive for 90+ days',
    category: 'time',
    severity: 'high',
    isActive: true,
    threshold: 90,
    action: 'review',
  },

  // Device Rules
  {
    id: 'rule-010',
    name: 'New Device Detection',
    description: 'Require OTP verification for transactions from unregistered devices',
    category: 'device',
    severity: 'medium',
    isActive: true,
    action: 'review',
  },
  {
    id: 'rule-011',
    name: 'Multiple Device Alert',
    description: 'Flag accounts accessed from more than 3 devices in 24 hours',
    category: 'device',
    severity: 'high',
    isActive: true,
    threshold: 3,
    action: 'flag',
  },
  {
    id: 'rule-012',
    name: 'Device-Location Mismatch',
    description: 'Block if device timezone differs significantly from transaction location',
    category: 'device',
    severity: 'critical',
    isActive: true,
    action: 'block',
  },

  // Pattern Rules
  {
    id: 'rule-013',
    name: 'Spending Pattern Deviation',
    description: 'Alert when transaction amount exceeds 3x user\'s average spending',
    category: 'pattern',
    severity: 'medium',
    isActive: true,
    threshold: 3,
    action: 'notify',
  },
  {
    id: 'rule-014',
    name: 'Merchant Category Anomaly',
    description: 'Flag unusual merchant categories for the user\'s transaction history',
    category: 'pattern',
    severity: 'low',
    isActive: true,
    action: 'flag',
  },
  {
    id: 'rule-015',
    name: 'Round Amount Pattern',
    description: 'Monitor multiple transactions with round amounts (₹10,000, ₹50,000)',
    category: 'pattern',
    severity: 'medium',
    isActive: true,
    action: 'review',
  },

  // Velocity Rules
  {
    id: 'rule-016',
    name: 'Daily Transaction Limit',
    description: 'Block if daily transaction count exceeds 20 transactions',
    category: 'velocity',
    severity: 'high',
    isActive: true,
    threshold: 20,
    action: 'block',
  },
  {
    id: 'rule-017',
    name: 'Hourly Velocity Check',
    description: 'Flag accounts with more than 5 transactions per hour',
    category: 'velocity',
    severity: 'medium',
    isActive: true,
    threshold: 5,
    action: 'flag',
  },
  {
    id: 'rule-018',
    name: 'Daily Amount Limit',
    description: 'Require additional verification if daily spend exceeds ₹10,00,000',
    category: 'velocity',
    severity: 'critical',
    isActive: true,
    threshold: 1000000,
    action: 'review',
  },

  // Cross-Institution Intelligence Rules
  {
    id: 'rule-019',
    name: 'Known Scam Beneficiary Match',
    description: 'Block transactions directed to beneficiary identifiers reported across consortium intelligence',
    category: 'intelligence',
    severity: 'critical',
    isActive: true,
    action: 'block',
  },
  {
    id: 'rule-020',
    name: 'Cross-Institution Device Match',
    description: 'Flag transactions originating from hardware fingerprints associated with multi-bank fraud',
    category: 'intelligence',
    severity: 'high',
    isActive: true,
    action: 'flag',
  },

  // Social Engineering Rules
  {
    id: 'rule-021',
    name: 'Social Engineering / Payment Urgency',
    description: 'Flag transactions initiated shortly after high-pressure phone interaction',
    category: 'social_engineering',
    severity: 'high',
    isActive: true,
    action: 'review',
  },
  {
    id: 'rule-022',
    name: 'Fake KYC / Account Closure Pressure',
    description: 'Block transactions showing signatures of impersonation scams or coercive account threats',
    category: 'social_engineering',
    severity: 'critical',
    isActive: true,
    action: 'block',
  },
]

